accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('password/change/', views.change_password, name='change_password'),
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('delete/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('edit/<int:contact_id>/', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

star/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Old Password')
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='New Password')
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm New Password')

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .forms import UserUpdateForm, PasswordChangingForm
from contacts.models import Contact

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists !')
                return redirect('accounts:register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email already exists !')
                    return redirect('accounts:register')
                else:
                    user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                    user.save()
                    messages.success(request, "Account created successfully !")
                    return redirect('accounts:login')
        else:
            messages.error(request, 'Password do not match !')
            return redirect('accounts:register')
    else:
        return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username,password=password)
        if user is not None:
            auth.login(request,user)
            messages.success(request,"You are now logged in !")
            return redirect('accounts:dashboard')
        else:
            messages.error(request,"Invalid credentials !")
            return redirect('accounts:login')
    else :
        return render(request, 'accounts/login.html')


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect("pages:index")

@login_required
def dashboard(request):
    user_form = UserUpdateForm(instance=request.user)
    password_form = PasswordChangingForm(request.user)
    contacts = Contact.objects.filter(user_id=request.user.id)
    context = {
        'user_form': user_form,
        'password_form': password_form,
        'contacts': contacts
    }
    return render(request, 'accounts/dashboard.html', context)

@login_required
def update_profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('accounts:dashboard')
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'accounts/update_profile.html', {'form': form})

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangingForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangingForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

templates/accounts/change_password.html
{% extends "base.html" %}

{% block title %} | Change Password {% endblock %}

{% block content %}
<section id="change_password" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4>
              <i class="fas fa-lock"></i> Change Password</h4>
          </div>
          <div class="card-body">
            <!-- Alerts -->
            {% include 'partials/_alert.html' %}
            <form action="{% url 'accounts:change_password' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="old_password">Old Password</label>
                {{ form.old_password }}
              </div>
              <div class="form-group">
                <label for="new_password1">New Password</label>
                {{ form.new_password1 }}
              </div>
              <div class="form-group">
                <label for="new_password2">Confirm New Password</label>
                {{ form.new_password2 }}
              </div>
              <input type="submit" value="Change Password" class="btn btn-secondary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/accounts/dashboard.html
{% extends "base.html" %}
{% block title %} | User: {{user.username}} {% endblock title %}
{% block content %}
{% include 'partials/_alert.html' %}
    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">User Dashboard</h1>
            <p class="lead">Manage your BC Real Estate account</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'pages:index' %}"> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">Dashboard</li>
          </ol>
        </nav>
      </div>
    </section>

    <section id="dashboard" class="py-4">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>Welcome {{ user.first_name | default:user.username }}</h2>
            <p class="mt-3">Here are the property listings that you have inquired about</p>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Property</th>
                  <th scope="col">Date</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts %}
                <tr>
                  <td>{{contact.listing_id}}</td>
                  <td>{{contact.listing}}</td>
                  <td>{{contact.contact_date|date:"M d, Y"}}</td>
                  <td>
                    {% if contact.message_updated_date %}
                      <small class="text-muted">
                        <i class="fas fa-edit"></i> Updated: {{contact.message_updated_date|date:"M d, Y"}}
                      </small>
                    {% endif %}
                  </td>
                  <td>
                    <!-- View Listing -->
                    <a class="btn btn-sm btn-info" href="{% url 'listings:listing' contact.listing_id %}">
                      View Listing
                    </a>
                    <!-- Edit -->
                    <a class="btn btn-sm btn-warning" href="{% url 'contacts:edit_contact' contact.id %}">
                      Edit
                     </a>
      
                    <!-- Delete -->
                    <form action="{% url 'contacts:delete_contact' contact.id %}" method="post" style="display:inline;">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you Sure?? [DELETE THIS ITEM]');">
                        Delete
                      </button>
                    </form>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="4">You have no inquiries</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %} 
{% block title %} | User Login {% endblock title %}
{% block content %}
    <section id="login" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include 'partials/_alert.html' %}
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-sign-in-alt"></i> Login</h4>
              </div>
              <div class="card-body">
                <form action={% url "accounts:login" %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>

                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Login"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %} 
{% block title %} | Registration {% endblock title %}
{% block content %}
    <section id="register" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include 'partials/_alert.html' %}
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Register</h4>
              </div>
              <div class="card-body">
                <form action={% url "accounts:register" %} method="POST" >
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input
                      id="first_name"
                      type="text"
                      name="first_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input
                      id="last_name"
                      type="text"
                      name="last_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input
                      id="password2"
                      type="password"
                      name="password2"
                      class="form-control"
                      required
                    />
                  </div>
                  <input
                    type="submit"
                    value="Register"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/accounts/update_profile.html
{% extends "base.html" %}

{% block title %} | Update Profile {% endblock %}

{% block content %}
<section id="update_profile" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4>
              <i class="fas fa-user-edit"></i> Update Profile</h4>
          </div>
          <div class="card-body">
            <!-- Alerts -->
            {% include 'partials/_alert.html' %}
            <form action="{% url 'accounts:update_profile' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="first_name">First Name</label>
                {{ form.first_name }}
              </div>
              <div class="form-group">
                <label for="last_name">Last Name</label>
                {{ form.last_name }}
              </div>
              <div class="form-group">
                <label for="username">Username</label>
                {{ form.username }}
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                {{ form.email }}
              </div>
              <input type="submit" value="Update" class="btn btn-secondary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}